### ISSUE TITLE
Transactions Configs - Shopify

### ISSUE THREAD

**Issue by valinhou** [anion0278/mapp#75]
Možnost konvertovat pohyby z shopify taky jako gpc

Určující částkou v souboru je "Presentment Amount"

Type: rozlišuje se charge (Order) a Refund
Variabilní symbol je z kolonky "Order" ..např. 3099.....v gpc je variabliní symbol 10 místný, takže nejspíš 0000003099

pak máme druhý eshop, který se exportovaným souborem neliší, ale je tam variabliní symbol 6 místný (např. 201023) takže v té variantě by to bylo 0000201023

Jestli můžu cokoliv zjednodušit u sebe, dej vědět.

[payment_transactions_export_1.csv](https://github.com/anion0278/mapp/files/13349237/payment_transactions_export_1.csv)

**Comment by anion0278** [comment]
@valinhou musime to probrat, nevim jake sloupce kam patri a nevim vsechny nazvy typu tranzakci
