### ISSUE TITLE
Error u Transactions Converter

### ISSUE THREAD

**Issue by valinhou** [anion0278/mapp#78]
![image](https://github.com/anion0278/mapp/assets/150779786/b9b95329-e075-4abe-bf42-505955b19623)

**Comment by anion0278** [comment]
@valinhou pošli mi k tomu soubor, který konvertujes

**Comment by valinhou** [comment]
je jich 14 z amazonu, 2 shoppay (payment_transactions_export, jsou stejné takže posílám jeden) a PayPal...posílám příklady, ale můžu klidně všechny pokud je potřeba
[payment_transactions_export_1.csv](https://github.com/anion0278/mapp/files/14885076/payment_transactions_export_1.csv)
[2024FebMonthlyUnifiedTransaction.csv](https://github.com/anion0278/mapp/files/14885022/2024FebMonthlyUnifiedTransaction.csv)
[2024FebMonthlyTransaction (2).csv](https://github.com/anion0278/mapp/files/14885025/2024FebMonthlyTransaction.2.csv)
+ dalších 12 amazonů, ten co je ve španělštině funguje

**Comment by anion0278** [comment]
@valinhou Potřeboval bych všechny v nějnovejsim formátu roku 2024,protoze podle všecho všude došlo ke změnám

**Comment by valinhou** [comment]
Já jsem to v průběhu let upravoval
Tady jsou soubory z mojí složky
[Transactions Configs.zip](https://github.com/anion0278/mapp/files/14886259/Transactions.Configs.zip)

Tady jsou všechny soubory pro Transactions Converter (aktuální z únor 2024)
[Soubory pro transaction converter.zip](https://github.com/anion0278/mapp/files/14886375/Soubory.pro.transaction.converter.zip)


pro jistotu posílám i aktuální soubory z invoice convertoru 
[Invoice Converter.zip](https://github.com/anion0278/mapp/files/14886280/Invoice.Converter.zip)

**Comment by valinhou** [comment]
Pořád nejde, error s Numéro de la commande
![image](https://github.com/anion0278/mapp/assets/150779786/1d6d60d4-5ccc-4039-a446-9615bf23de90)
